# Generated by Django 5.1.3 on 2025-03-06 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_short', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturl',
            old_name='original_Url',
            new_name='original_url',
        ),
    ]
